# Build: public datasets for the wider complement / C4b exploration

Downloads are done outside the notebook (`scripts/download_public_datasets.sh`). This notebook turns the downloaded files into harmonised `.h5ad` objects using the loaders in `scripts/oligoc4b_public.py`.

| Dataset | Accession | Species / modality | Comparison | Why |
| --- | --- | --- | --- | --- |
| Park et al. 2023 AD hippocampus | GSE224398 | mouse scRNA-seq | App^NL-G-F^ vs control, 1/3/6 mo | the dataset in which the C4b⁺ DA-oligodendrocyte state was described |
| Aging snRNA-seq HIP + CP | GSE212576 | mouse snRNA-seq | old vs young | aging counterpart already used in this repo |
| Ximerakis et al. 2019 | GSE129788 | mouse scRNA-seq, whole brain | old vs young | independent aging dataset with author cell types |
| Kaya et al. 2022 | GSE202579 | mouse scRNA-seq, white vs grey matter | WM vs GM at 24 mo (WT, Rag1-KO) | interferon-responsive oligodendrocytes in aging white matter |
| Zhou et al. 2020 | GSE140511 | mouse snRNA-seq, cortex + hippocampus | 5XFAD vs non-Tg (± Trem2-KO) | second AD model |
| Chen et al. 2020 | GSE152506 | mouse Spatial Transcriptomics | App^NL-G-F^ vs WT, 3–18 mo | whole-transcriptome spatial AD data; C4b is a plaque-induced gene |
| Jäkel et al. 2019 | GSE118257 | human snRNA-seq, MS white matter | MS lesions vs control | human MS oligodendrocytes |
| Absinta et al. 2021 | GSE180759 | human snRNA-seq, chronic active MS lesions | lesion edge / core / periplaque vs control | human MS lesion rim biology |
| Leng et al. 2021 | GSE147528 | human snRNA-seq, SFG + EC | Braak 6 vs Braak 0 (Braak 2 intermediate) | human AD across pathological stages |
| Sadick et al. 2022 | GSE167494 | human snRNA-seq, PFC, astrocyte/oligodendrocyte-enriched | AD vs non-symptomatic | human AD oligodendrocytes at depth |
| LPC + cuprizone corpus callosum | GSE293850 | mouse snRNA-seq | LPC / cuprizone vs saline | toxic demyelination without adaptive immunity |
| Serpina3n cKO + cuprizone | GSE319903 | mouse snRNA-seq | cuprizone vs normal diet; Serpina3n cKO | Serpina3n is the top C4b-correlated gene in every dataset |
| Lerma-Martin et al. 2024 (snRNA) | GSE279180 | human snRNA-seq, subcortical MS lesions | chronic active / inactive vs control | third human MS single-nucleus dataset, author-annotated |
| Lerma-Martin et al. 2024 (Visium) | GSE279181 | human Visium | same lesions | human MS spatial, whole transcriptome |
| Senescent-like glia in MS, 2025 | GSE277435 | human Visium | MS vs control | second human MS spatial dataset |
| Schirmer et al. 2019 | UCSC `ms` | human snRNA-seq, MS lesions | lesion types vs control | fourth human MS single-nucleus dataset |

Harmonised `obs` columns: `dataset`, `species`, `modality`, `sample`, `group` (comparison level), `group_ref`, `cell_type_coarse`, `cell_type_original`, and `condition_original` for the human lesion / Braak labels. Coarse cell types come from author annotations when provided, otherwise from marker-based cluster annotation (`annotate_by_markers`).

Environment: `OLIGOC4B_PUBLIC_RAW_DIR` (downloaded files, one folder per accession) and `OLIGOC4B_PUBLIC_PROCESSED_DIR` (output).

In [1]:
import os, sys, warnings
warnings.filterwarnings("ignore")
sys.path.insert(0, "../../scripts")
import importlib, oligoc4b_public as pub
importlib.reload(pub)
import pandas as pd
print("raw:", pub.RAW_DIR); print("processed:", pub.PROCESSED_DIR)
print("available loaders:", list(pub.LOADERS))

raw: /Volumes/jamboree/OligoC4b_public/raw
processed: /Volumes/jamboree/OligoC4b_public/processed
available loaders: ['Park2023_AD_hippocampus_scRNA', 'Aging_snRNA_HIP_CP_mouse', 'Ximerakis2019_aging_brain_scRNA', 'Zhou2020_5XFAD_snRNA', 'Jakel2019_MS_human_snRNA', 'Absinta2021_MS_human_snRNA', 'Chen2020_ST_AppNLGF_mouse', 'Kaya2022_aged_WM_vs_GM_scRNA', 'Leng2021_AD_human_snRNA', 'Sadick2022_AD_human_astro_oligo_snRNA', 'LPC_Cuprizone_CC_snRNA_mouse', 'Serpina3n_Cuprizone_snRNA_mouse', 'LermaMartin2024_MS_human_snRNA', 'LermaMartin2024_MS_human_Visium', 'SenescentGlia2025_MS_human_Visium', 'Schirmer2019_MS_human_snRNA']

In [2]:
built = pub.build_all(overwrite=False)
built

[skip] Park2023_AD_hippocampus_scRNA exists
[skip] Aging_snRNA_HIP_CP_mouse exists
[skip] Ximerakis2019_aging_brain_scRNA exists
[skip] Zhou2020_5XFAD_snRNA exists
[skip] Jakel2019_MS_human_snRNA exists
[skip] Absinta2021_MS_human_snRNA exists
[skip] Chen2020_ST_AppNLGF_mouse exists
[skip] Kaya2022_aged_WM_vs_GM_scRNA exists
[skip] Leng2021_AD_human_snRNA exists
[skip] Sadick2022_AD_human_astro_oligo_snRNA exists
[skip] LPC_Cuprizone_CC_snRNA_mouse exists
[skip] Serpina3n_Cuprizone_snRNA_mouse exists
[skip] LermaMartin2024_MS_human_snRNA exists
[skip] LermaMartin2024_MS_human_Visium exists
[skip] SenescentGlia2025_MS_human_Visium exists
[skip] Schirmer2019_MS_human_snRNA exists

{'Park2023_AD_hippocampus_scRNA': '/Volumes/jamboree/OligoC4b_public/processed/Park2023_AD_hippocampus_scRNA.h5ad',
 'Aging_snRNA_HIP_CP_mouse': '/Volumes/jamboree/OligoC4b_public/processed/Aging_snRNA_HIP_CP_mouse.h5ad',
 'Ximerakis2019_aging_brain_scRNA': '/Volumes/jamboree/OligoC4b_public/processed/Ximerakis2019_aging_brain_scRNA.h5ad',
 'Zhou2020_5XFAD_snRNA': '/Volumes/jamboree/OligoC4b_public/processed/Zhou2020_5XFAD_snRNA.h5ad',
 'Jakel2019_MS_human_snRNA': '/Volumes/jamboree/OligoC4b_public/processed/Jakel2019_MS_human_snRNA.h5ad',
 'Absinta2021_MS_human_snRNA': '/Volumes/jamboree/OligoC4b_public/processed/Absinta2021_MS_human_snRNA.h5ad',
 'Chen2020_ST_AppNLGF_mouse': '/Volumes/jamboree/OligoC4b_public/processed/Chen2020_ST_AppNLGF_mouse.h5ad',
 'Kaya2022_aged_WM_vs_GM_scRNA': '/Volumes/jamboree/OligoC4b_public/processed/Kaya2022_aged_WM_vs_GM_scRNA.h5ad',
 'Leng2021_AD_human_snRNA': '/Volumes/jamboree/OligoC4b_public/processed/Leng2021_AD_human_snRNA.h5ad',
 'Sadick2022_AD_human_astro_oligo_snRNA': '/Volumes/jamboree/OligoC4b_public/processed/Sadick2022_AD_human_astro_oligo_snRNA.h5ad',
 'LPC_Cuprizone_CC_snRNA_mouse': '/Volumes/jamboree/OligoC4b_public/processed/LPC_Cuprizone_CC_snRNA_mouse.h5ad',
 'Serpina3n_Cuprizone_snRNA_mouse': '/Volumes/jamboree/OligoC4b_public/processed/Serpina3n_Cuprizone_snRNA_mouse.h5ad',
 'LermaMartin2024_MS_human_snRNA': '/Volumes/jamboree/OligoC4b_public/processed/LermaMartin2024_MS_human_snRNA.h5ad',
 'LermaMartin2024_MS_human_Visium': '/Volumes/jamboree/OligoC4b_public/processed/LermaMartin2024_MS_human_Visium.h5ad',
 'SenescentGlia2025_MS_human_Visium': '/Volumes/jamboree/OligoC4b_public/processed/SenescentGlia2025_MS_human_Visium.h5ad',
 'Schirmer2019_MS_human_snRNA': '/Volumes/jamboree/OligoC4b_public/processed/Schirmer2019_MS_human_snRNA.h5ad'}

In [3]:
import scanpy as sc
rows = []
for name, path in pub.processed_paths().items():
    a = sc.read_h5ad(path, backed="r")
    o = a.obs
    rows.append({"dataset": name, "n_cells": a.n_obs, "n_genes": a.n_vars, "species": o["species"].iloc[0], "modality": o["modality"].iloc[0],
                 "n_samples": o["sample"].nunique(), "groups": o["group"].value_counts().to_dict(),
                 "oligodendrocytes": int((o["cell_type_coarse"].astype(str) == "Oligodendrocyte").sum()),
                 "microglia": int((o["cell_type_coarse"].astype(str) == "Microglia").sum())})
summary = pd.DataFrame(rows).set_index("dataset")
pd.set_option("display.width", 200); pd.set_option("display.max_colwidth", 80)
display(summary)

                                       n_cells  n_genes species modality  n_samples                                           groups  oligodendrocytes  microglia
dataset
Absinta2021_MS_human_snRNA               66432    27807   human    snRNA          8                      {'MS': 61141, 'Ctrl': 5291}             45697       5432
Aging_snRNA_HIP_CP_mouse                109822    27213   mouse    snRNA          8                   {'Young': 60384, 'Old': 49438}             19593       3112
Chen2020_ST_AppNLGF_mouse                19021    44669   mouse  spatial         20                         {'WT': 9542, 'AD': 9479}                 0          0
Jakel2019_MS_human_snRNA                 17790    21349   human    snRNA         20                      {'MS': 11199, 'Ctrl': 6591}              7973        428
Kaya2022_aged_WM_vs_GM_scRNA             29623    20027   mouse    scRNA          8                        {'WM': 23391, 'GM': 6232}             15776       5054
LPC_Cuprizone_CC_snRNA_mouse             30338    25075   mouse    snRNA          8  {'Ctrl': 14550, 'LPC': 9493, 'Cuprizone': 6295}             12880       5820
Leng2021_AD_human_snRNA                  92199    29056   human    snRNA         20                     {'AD': 51980, 'Ctrl': 40219}             26808       4460
LermaMartin2024_MS_human_Visium          70238    25499   human  spatial         18                     {'MS': 45870, 'Ctrl': 24368}                 0          0
LermaMartin2024_MS_human_snRNA          102672    31203   human    snRNA         16                     {'MS': 73637, 'Ctrl': 29035}             64833       9238
Park2023_AD_hippocampus_scRNA            47660    21809   mouse    scRNA          6                       {'AD': 27003, 'WT': 20657}             10237      13952
Sadick2022_AD_human_astro_oligo_snRNA   107392    32263   human    snRNA         17                     {'AD': 64500, 'Ctrl': 42892}             33750          0
Schirmer2019_MS_human_snRNA              48919    33741   human    snRNA         21                     {'MS': 31516, 'Ctrl': 17403}             12394       1425
SenescentGlia2025_MS_human_Visium        27619    22052   human  spatial         12                                    {'MS': 27619}                 0          0
Serpina3n_Cuprizone_snRNA_mouse          52437    27508   mouse    snRNA          5              {'Cuprizone': 34123, 'Ctrl': 18314}              8207       2413
Ximerakis2019_aging_brain_scRNA          37069    14698   mouse    scRNA         16                   {'Old': 21041, 'Young': 16028}             12384       3910
Zhou2020_5XFAD_snRNA                    125858    24693   mouse    snRNA         20                       {'WT': 69841, 'AD': 56017}             17356       4152

In [4]:
# sanity check of the coarse annotation: composition per dataset, author labels vs coarse types, and canonical markers
import numpy as np, scipy.sparse as sp
for name, path in pub.processed_paths().items():
    a = sc.read_h5ad(path, backed="r")
    ct = a.obs["cell_type_coarse"].astype(str)
    print(f"\n{name}: ", ct.value_counts().to_dict())
    if "cell_type_original" in a.obs and a.obs["cell_type_original"].nunique() < 60:
        cross = pd.crosstab(a.obs["cell_type_original"].astype(str), ct)
        display(cross.loc[cross.sum(axis=1).sort_values(ascending=False).index[:25]])
    markers = {"Oligodendrocyte": "Plp1", "Microglia": "Hexb", "Astrocyte": "Aqp4", "Neuron": "Snap25", "OPC": "Pdgfra"}
    if a.obs["species"].iloc[0] == "human":
        markers = {k: v.upper() for k, v in markers.items()}
    rows = {}
    for k, g in markers.items():
        if g not in a.var_names:
            continue
        x = a[:, g].to_memory().X
        x = np.asarray(x.todense()).ravel() if sp.issparse(x) else np.asarray(x).ravel()
        rows[g] = {c: round(float((x[ct.values == c] > 0).mean()), 2) for c in ["Oligodendrocyte", "OPC", "Microglia", "Astrocyte", "Neuron"] if (ct.values == c).sum() > 0}
    if rows:
        print("fraction of cells detecting each marker, by coarse type:"); display(pd.DataFrame(rows).T)

Absinta2021_MS_human_snRNA:  {'Oligodendrocyte': 45697, 'Astrocyte': 8211, 'Microglia': 5432, 'Neuron': 2803, 'OPC': 2175, 'Vascular/Fibroblast': 1708, 'Immune (lymphoid/myeloid)': 406}

cell_type_coarse    Astrocyte  Immune (lymphoid/myeloid)  Microglia  Neuron   OPC  Oligodendrocyte  Vascular/Fibroblast
cell_type_original
oligodendrocytes            0                          0          0       0     0            45697                    0
astrocytes               8211                          0          0       0     0                0                    0
immune                      0                          0       5432       0     0                0                    0
neurons                     0                          0          0    2803     0                0                    0
opc                         0                          0          0       0  2175                0                    0
vascular_cells              0                          0          0       0     0                0                 1708
lymphocytes                 0                        406          0       0     0                0                    0

fraction of cells detecting each marker, by coarse type:

        Oligodendrocyte   OPC  Microglia  Astrocyte  Neuron
PLP1               0.96  0.43       0.34       0.34    0.25
HEXB               0.07  0.08       0.15       0.04    0.09
AQP4               0.03  0.06       0.05       0.62    0.08
SNAP25             0.04  0.41       0.04       0.11    0.77
PDGFRA             0.00  0.37       0.00       0.00    0.00

Aging_snRNA_HIP_CP_mouse:  {'Neuron': 67036, 'Oligodendrocyte': 19593, 'Astrocyte': 12690, 'OPC': 4754, 'Microglia': 3112, 'Vascular/Fibroblast': 1065, 'Endothelial': 1012, 'Immune (lymphoid/myeloid)': 350, 'Ependymal': 210}

fraction of cells detecting each marker, by coarse type:

        Oligodendrocyte   OPC  Microglia  Astrocyte  Neuron
Plp1               0.98  0.46       0.45       0.41    0.42
Hexb               0.08  0.06       0.92       0.09    0.10
Aqp4               0.03  0.10       0.05       0.48    0.03
Snap25             0.37  0.49       0.37       0.38    0.98
Pdgfra             0.01  0.35       0.01       0.02    0.01

Chen2020_ST_AppNLGF_mouse:  {'spot': 19021}

fraction of cells detecting each marker, by coarse type:

Empty DataFrame
Columns: []
Index: [Plp1, Hexb, Aqp4, Snap25, Pdgfra]

Jakel2019_MS_human_snRNA:  {'Oligodendrocyte': 7973, 'Neuron': 5031, 'Astrocyte': 1242, 'Endothelial': 836, 'Immune (lymphoid/myeloid)': 782, 'Vascular/Fibroblast': 697, 'Other': 449, 'Microglia': 428, 'OPC': 352}

cell_type_coarse       Astrocyte  Endothelial  Immune (lymphoid/myeloid)  Microglia  Neuron  OPC  Oligodendrocyte  Other  Vascular/Fibroblast
cell_type_original
Oligo2                         0            0                          0          0       0    0             1839      0                    0
Oligo4                         0            0                          0          0       0    0             1579      0                    0
Neuron1                        0            0                          0          0    1507    0                0      0                    0
Oligo6                         0            0                          0          0       0    0             1484      0                    0
Neuron2                        0            0                          0          0    1438    0                0      0                    0
Oligo5                         0            0                          0          0       0    0             1167      0                    0
Oligo1                         0            0                          0          0       0    0             1129      0                    0
Astrocytes                  1046            0                          0          0       0    0                0      0                    0
Neuron4                        0            0                          0          0     948    0                0      0                    0
Oligo3                         0            0                          0          0       0    0              775      0                    0
Neuron5                        0            0                          0          0     595    0                0      0                    0
Pericytes                      0            0                          0          0       0    0                0      0                  585
Neuron3                        0            0                          0          0     543    0                0      0                    0
Endothelial_cells1             0          452                          0          0       0    0                0      0                    0
Microglia_Macrophages          0            0                          0        428       0    0                0      0                    0
Immune_cells                   0            0                        420          0       0    0                0      0                    0
Endothelial_cells2             0          384                          0          0       0    0                0      0                    0
Macrophages                    0            0                        362          0       0    0                0      0                    0
OPCs                           0            0                          0          0       0  352                0      0                    0
COPs                           0            0                          0          0       0    0                0    242                    0
ImOlGs                         0            0                          0          0       0    0                0    207                    0
Astrocytes2                  196            0                          0          0       0    0                0      0                    0
Vasc_smooth_muscle             0            0                          0          0       0    0                0      0                  112

fraction of cells detecting each marker, by coarse type:

        Oligodendrocyte   OPC  Microglia  Astrocyte  Neuron
PLP1               0.99  0.35       0.31       0.42    0.34
HEXB               0.02  0.03       0.05       0.03    0.08
AQP4               0.03  0.06       0.05       0.71    0.06
SNAP25             0.08  0.23       0.05       0.14    0.94
PDGFRA             0.00  0.35       0.00       0.00    0.01

Kaya2022_aged_WM_vs_GM_scRNA:  {'Oligodendrocyte': 15776, 'Immune (lymphoid/myeloid)': 5877, 'Microglia': 5054, 'Astrocyte': 1933, 'Neuron': 546, 'Endothelial': 181, 'Ependymal': 166, 'OPC': 90}

fraction of cells detecting each marker, by coarse type:

        Oligodendrocyte   OPC  Microglia  Astrocyte  Neuron
Plp1               1.00  0.94       0.76       0.71    0.92
Hexb               0.41  0.46       0.99       0.34    0.30
Aqp4               0.02  0.18       0.03       0.65    0.02
Snap25             0.01  0.43       0.01       0.03    0.33
Pdgfra             0.00  0.98       0.00       0.00    0.01

LPC_Cuprizone_CC_snRNA_mouse:  {'Oligodendrocyte': 12880, 'Microglia': 5820, 'Neuron': 4343, 'OPC': 3130, 'Immune (lymphoid/myeloid)': 2680, 'Astrocyte': 835, 'Vascular/Fibroblast': 550, 'Ependymal': 100}

fraction of cells detecting each marker, by coarse type:

        Oligodendrocyte   OPC  Microglia  Astrocyte  Neuron
Plp1               0.99  0.81       0.75       0.74    0.63
Hexb               0.25  0.37       0.96       0.37    0.29
Aqp4               0.02  0.05       0.09       0.50    0.02
Snap25             0.13  0.28       0.07       0.12    0.89
Pdgfra             0.01  0.32       0.01       0.00    0.01

Leng2021_AD_human_snRNA:  {'Neuron': 40386, 'Oligodendrocyte': 26808, 'Astrocyte': 11901, 'OPC': 5605, 'Microglia': 4460, 'Immune (lymphoid/myeloid)': 2110, 'Endothelial': 929}

fraction of cells detecting each marker, by coarse type:

        Oligodendrocyte   OPC  Microglia  Astrocyte  Neuron
PLP1               0.90  0.16       0.13       0.17    0.18
HEXB               0.04  0.06       0.08       0.04    0.15
AQP4               0.02  0.03       0.02       0.53    0.04
SNAP25             0.20  0.38       0.18       0.23    0.80
PDGFRA             0.00  0.22       0.00       0.00    0.01

LermaMartin2024_MS_human_Visium:  {'spot': 70238}

fraction of cells detecting each marker, by coarse type:

Empty DataFrame
Columns: []
Index: [PLP1, HEXB, AQP4, SNAP25, PDGFRA]

LermaMartin2024_MS_human_snRNA:  {'Oligodendrocyte': 64833, 'Astrocyte': 13985, 'Microglia': 9238, 'Neuron': 8171, 'OPC': 3945, 'Endothelial': 2230, 'Immune (lymphoid/myeloid)': 270}

fraction of cells detecting each marker, by coarse type:

        Oligodendrocyte   OPC  Microglia  Astrocyte  Neuron
PLP1               0.90  0.09       0.02       0.04    0.13
HEXB               0.08  0.11       0.21       0.06    0.30
AQP4               0.00  0.01       0.00       0.76    0.01
SNAP25             0.02  0.44       0.00       0.05    0.94
PDGFRA             0.00  0.79       0.00       0.00    0.04

Park2023_AD_hippocampus_scRNA:  {'Microglia': 13952, 'Oligodendrocyte': 10237, 'Astrocyte': 7470, 'Endothelial': 5107, 'Neuron': 3298, 'OPC': 2471, 'Ependymal': 1906, 'Immune (lymphoid/myeloid)': 1644, 'Vascular/Fibroblast': 1575}

fraction of cells detecting each marker, by coarse type:

        Oligodendrocyte   OPC  Microglia  Astrocyte  Neuron
Plp1               1.00  0.79       0.74       0.83    0.82
Hexb               0.43  0.44       0.98       0.42    0.37
Aqp4               0.08  0.63       0.05       0.51    0.07
Snap25             0.02  0.04       0.01       0.01    0.08
Pdgfra             0.00  0.04       0.00       0.00    0.01

Sadick2022_AD_human_astro_oligo_snRNA:  {'Astrocyte': 47240, 'Oligodendrocyte': 33750, 'Neuron': 12399, 'OPC': 7116, 'Immune (lymphoid/myeloid)': 3556, 'Vascular/Fibroblast': 2465, 'Endothelial': 866}

fraction of cells detecting each marker, by coarse type:

        Oligodendrocyte   OPC  Astrocyte  Neuron
PLP1               0.87  0.19       0.13    0.13
HEXB               0.09  0.14       0.13    0.30
AQP4               0.16  0.59       0.92    0.27
SNAP25             0.10  0.39       0.22    0.85
PDGFRA             0.00  0.38       0.01    0.04

Schirmer2019_MS_human_snRNA:  {'Other': 18272, 'Oligodendrocyte': 12394, 'Neuron': 6917, 'Astrocyte': 5381, 'OPC': 3844, 'Microglia': 1425, 'Endothelial': 375, 'Immune (lymphoid/myeloid)': 158, 'Vascular/Fibroblast': 153}

cell_type_coarse    Astrocyte  Endothelial  Immune (lymphoid/myeloid)  Microglia  Neuron   OPC  Oligodendrocyte  Other  Vascular/Fibroblast
cell_type_original
OL-A                        0            0                          0          0       0     0             9642      0                    0
Astrocytes               5381            0                          0          0       0     0                0      0                    0
OPC                         0            0                          0          0       0  3844                0      0                    0
EN-L2-3-B                   0            0                          0          0       0     0                0   3291                    0
EN-L4                       0            0                          0          0       0     0                0   3125                    0
EN-L5-6                     0            0                          0          0       0     0                0   3058                    0
EN-L2-3-A                   0            0                          0          0       0     0                0   2829                    0
IN-VIP                      0            0                          0          0    2755     0                0      0                    0
EN-MIX                      0            0                          0          0       0     0                0   2403                    0
EN-PYR                      0            0                          0          0       0     0                0   2082                    0
IN-PVALB                    0            0                          0          0    1897     0                0      0                    0
OL-C                        0            0                          0          0       0     0             1598      0                    0
IN-SST                      0            0                          0          0    1486     0                0      0                    0
Microglia                   0            0                          0       1425       0     0                0      0                    0
Glia-MIX                    0            0                          0          0       0     0                0   1226                    0
OL-B                        0            0                          0          0       0     0             1154      0                    0
IN-SV2C                     0            0                          0          0     779     0                0      0                    0
Endo cells                  0          375                          0          0       0     0                0      0                    0
Phagocytes                  0            0                          0          0       0     0                0    258                    0
Stromal cells               0            0                          0          0       0     0                0      0                  153
T cells                     0            0                        105          0       0     0                0      0                    0
B cells                     0            0                         53          0       0     0                0      0                    0

fraction of cells detecting each marker, by coarse type:

        Oligodendrocyte   OPC  Microglia  Astrocyte  Neuron
PLP1               0.98  0.26       0.21       0.19    0.20
HEXB               0.03  0.06       0.08       0.03    0.15
AQP4               0.02  0.04       0.03       0.71    0.03
SNAP25             0.18  0.49       0.20       0.26    0.86
PDGFRA             0.00  0.35       0.00       0.00    0.03

SenescentGlia2025_MS_human_Visium:  {'spot': 27619}

fraction of cells detecting each marker, by coarse type:

Empty DataFrame
Columns: []
Index: [PLP1, HEXB, AQP4, SNAP25, PDGFRA]

Serpina3n_Cuprizone_snRNA_mouse:  {'Neuron': 30390, 'Oligodendrocyte': 8207, 'OPC': 4186, 'Astrocyte': 2968, 'Microglia': 2413, 'Ependymal': 2307, 'Vascular/Fibroblast': 1238, 'Endothelial': 427, 'Immune (lymphoid/myeloid)': 301}

fraction of cells detecting each marker, by coarse type:

        Oligodendrocyte   OPC  Microglia  Astrocyte  Neuron
Plp1               0.75  0.33       0.41       0.39    0.34
Hexb               0.13  0.17       0.38       0.09    0.13
Aqp4               0.05  0.02       0.02       0.32    0.02
Snap25             0.87  0.91       0.57       0.71    0.98
Pdgfra             0.04  0.25       0.02       0.02    0.02

Ximerakis2019_aging_brain_scRNA:  {'Oligodendrocyte': 12384, 'Astrocyte': 6747, 'Other': 5301, 'Microglia': 3910, 'Endothelial': 2413, 'OPC': 2187, 'Vascular/Fibroblast': 1655, 'Neuron': 1368, 'Immune (lymphoid/myeloid)': 700, 'Ependymal': 404}

cell_type_coarse    Astrocyte  Endothelial  Ependymal  Immune (lymphoid/myeloid)  Microglia  Neuron   OPC  Oligodendrocyte  Other  Vascular/Fibroblast
cell_type_original
OLG                         0            0          0                          0          0       0     0            12384      0                    0
ASC                      6747            0          0                          0          0       0     0                0      0                    0
mNEUR                       0            0          0                          0          0       0     0                0   5135                    0
MG                          0            0          0                          0       3910       0     0                0      0                    0
EC                          0         2413          0                          0          0       0     0                0      0                    0
OPC                         0            0          0                          0          0       0  2187                0      0                    0
OEG                         0            0          0                          0          0     892     0                0      0                    0
PC                          0            0          0                          0          0       0     0                0      0                  735
NendC                       0            0          0                          0          0     394     0                0      0                    0
MAC                         0            0          0                        377          0       0     0                0      0                    0
ABC                         0            0          0                          0          0       0     0                0      0                  307
EPC                         0            0        274                          0          0       0     0                0      0                    0
VSMC                        0            0          0                          0          0       0     0                0      0                  243
ARP                         0            0          0                          0          0       0     0                0      0                  184
NSC                         0            0          0                          0          0       0     0                0    166                    0
ImmN                        0            0          0                        162          0       0     0                0      0                    0
VLMC                        0            0          0                          0          0       0     0                0      0                  105
CPC                         0            0         89                          0          0       0     0                0      0                    0
NRP                         0            0          0                          0          0      82     0                0      0                    0
Hb_VC                       0            0          0                          0          0       0     0                0      0                   81
MNC                         0            0          0                         77          0       0     0                0      0                    0
DC                          0            0          0                         55          0       0     0                0      0                    0
NEUT                        0            0          0                         29          0       0     0                0      0                    0
TNC                         0            0         29                          0          0       0     0                0      0                    0
HypEPC                      0            0         12                          0          0       0     0                0      0                    0

fraction of cells detecting each marker, by coarse type:

        Oligodendrocyte   OPC  Microglia  Astrocyte  Neuron
Plp1               1.00  0.57       0.25       0.33    0.80
Hexb               0.10  0.12       1.00       0.15    0.13
Aqp4               0.02  0.05       0.02       0.73    0.02
Snap25             0.10  0.25       0.09       0.11    0.36
Pdgfra             0.00  0.84       0.00       0.01    0.01

Zhou2020_5XFAD_snRNA:  {'Neuron': 91680, 'Oligodendrocyte': 17356, 'Astrocyte': 7217, 'Microglia': 4152, 'OPC': 3261, 'Vascular/Fibroblast': 2192}

fraction of cells detecting each marker, by coarse type:

        Oligodendrocyte   OPC  Microglia  Astrocyte  Neuron
Plp1               0.99  0.60       0.43       0.43    0.37
Hexb               0.12  0.13       0.96       0.15    0.13
Aqp4               0.01  0.05       0.01       0.49    0.01
Snap25             0.35  0.50       0.37       0.34    0.76
Pdgfra             0.02  0.85       0.01       0.03    0.01